apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openai-proxy
  namespace: argocd
spec:
  destination:
    namespace: openai-proxy
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/fhswf/openai-proxy.git
    directory:
      exclude: config.yaml
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
