apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openai-proxy
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/fhswf/openai-proxy
spec:
  destination:
    namespace: openai-proxy
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/fhswf/openai-proxy.git
    directory:
      exclude: config.yaml
    targetRevision: HEAD
