---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  namespace: openai-proxy
  name: openai-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /openai/api
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxy
  namespace: openai-proxy
spec:
  entryPoints:
    - web-secure
  routes:
    - kind: Rule
      match: Host(`login.ki.fh-swf.de`) && PathPrefix(`/openai/api`)
      priority: 10
      services:
        - kind: Service
          name: proxy
          namespace: openai-proxy
          port: 3000
      middlewares:
        - name: openai-stripprefix
  tls:
    certResolver: default
