apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kubernetes.service: mongodb
    io.kubernetes.part-of: openai-proxy
  name: mongodb
  namespace: openai-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
        - image: mongo:4.4
          name: mongodb
          ports:
            - containerPort: 27017
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
            requests:
              memory: 64Mi
              cpu: 250m
