---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: openai-proxy
  labels:
    io.kubernetes.service: mongodb
    io.kubernetes.part-of: openai-proxy
    app: openai-proxy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kubernetes.service: mongodb
    io.kubernetes.part-of: openai-proxy
  name: mongodb
  namespace: openai-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openai-proxy
      tier: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mongodb
        app: openai-proxy
        tier: mongodb
    spec:
      containers:
        - image: mongo:5.0.31
          name: mongodb
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: data
          resources:
            limits:
              memory: 5Gi
              cpu: 500m
            requests:
              memory: 2Gi
              cpu: 250m
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongodb-pvc
