name: build

on: 
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ghcr.io/fhswf/openai-proxy:latest, ghcr.io/fhswf/openai-proxy:${{ github.sha }}

        - name: Update yaml
          uses: fjogeleit/yaml-update-action@main
          with:
            valueFile: 'k8s/deployment.yaml'
            propertyPath: 'spec.template.spec.containers[0].image'
            value: ghcr.io/fhswf/openai-proxy:${{ github.sha }}
            branch: main
            message: 'Update image to ${{ github.sha }}'